{
 "title": "Generic Value",
 "tags": [
  "dev",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(nq_counter_value_count, workspace)"
    }
   },
   {
    "name": "application_role",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\"}, application_role)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\",application_role=~\"${application_role}\"}, instance)"
    }
   },
   {
    "name": "grain",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\"}, currentGrain)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\",grain=~\"^${grain}$\"}, method)"
    }
   },
   {
    "name": "category",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"$grain\"}, category)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"$grain\",category=~\"$category\"}, name)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"$grain\",category=~\"$category\", name=~\"$name\"}, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "category" },
  {
   "title": "grain rps on \"${grain}\" \"$category\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (category,name,type) (rate(nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\",category=~\"$category\",name=~\"$name\",type=~\"$type\"}[$__rate_interval])) ",
     "legendFormat": "{{name}} {{type}}"
    }
   ]
  },
  {
   "title": "Heatmap of ${grain} $category for $name",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(nq_counter_value_bucket{instance=~\"${instance}\",currentGrain=~\"^${grain}$\",currentMethod=~\"^$method$\",category=\"$category\",name=~\"$name\",type=~\"$type\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "average value on \"${grain}\" $category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (name,type) (rate (nq_counter_value_sum{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\",name=~\"$name\",type=~\"$type\"}[$__rate_interval]))) / (sum by (name,type) (rate (nq_counter_value_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\",name=~\"$name\",type=~\"$type\"}[$__rate_interval])))",
     "legendFormat": "{{category}} {{name}} {{type}}"
    }
   ]
  }
 ]
}