{
 "title": "Generic Request Detailed",
 "tags": [
  "orleans",
  "dev",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(nq_request_duration_count, workspace)"
    }
   },
   {
    "name": "application_role",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\"}, application_role)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"${application_role}\"}, instance)"
    }
   },
   {
    "name": "category",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\"}, category)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",category=\"$category\"}, name)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",category=\"$category\",name=\"$name\"}, type)"
    }
   },
   {
    "name": "grain",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",category=\"$category\",name=\"$name\"}, currentGrain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "grain rps on  \"$category\" \"$name\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (currentGrain,currentMethod,type) (rate(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"^$grain$\",category=~\"$category\",name=~\"^$name$\",type=~\"$type\"}[$__rate_interval])) ",
     "legendFormat": "{{currentGrain}} {{currentMethod}} {{type}}"
    }
   ]
  },
  {
   "title": "average request duration on \"${grain}\" $category $name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (currentGrain,type) (rate (nq_request_duration_sum{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",category=\"$category\",name=~\"^$name$\",type=~\"$type\"}[$__rate_interval]))) / (sum by (currentGrain, type) (rate (nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",category=\"$category\",name=~\"^$name$\",type=~\"$type\"}[$__rate_interval])))",
     "legendFormat": "{{currentGrain}} {{type}}"
    }
   ]
  },
  {
   "title": "Heatmap of ${grain} $category $name",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(nq_request_duration_bucket{application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"^${grain}$\",category=\"$category\",name=~\"^$name$\",type=~\"$type\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "flying request for $grain $category-$name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by (currentGrain,currentMethod,type) (max_over_time(nq_request_flying{instance=~\"${instance}\",currentGrain=~\"${grain}\",category=\"$category\",name=~\"^$name$\",type=~\"$type\"}[$__rate_interval]))",
     "legendFormat": "{{currentGrain}} {{currentMethod}} {{type}}"
    }
   ]
  },
  {
   "title": "success rate on \"${grain}\" $category $name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (currentGrain,currentMethod,type) (rate (nq_request_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"${grain}\",category=\"$category\",name=~\"^$name$\",type=~\"$type\",success=\"True\"}[$__rate_interval]))) / (sum by (currentGrain,currentMethod,type) (rate (nq_request_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=~\"${grain}\",category=\"$category\",name=~\"^$name$\",type=~\"$type\"}[$__rate_interval])))",
     "legendFormat": "{{currentGrain}} {{currentMethod}} {{type}}"
    }
   ]
  }
 ]
}