{
 "title": "Orleans",
 "tags": [
  "orleans",
  "dev"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(orleans_requests_duration_count, workspace)"
    }
   },
   {
    "name": "application_role",
    "query": {
     "query": "label_values(orleans_requests_duration_count{workspace=\"${workspace}\"}, application_role)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(orleans_requests_duration_count{workspace=\"${workspace}\",application_role=~\"${application_role}\"}, instance)"
    }
   },
   {
    "name": "grain",
    "query": {
     "query": "label_values(orleans_requests_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\"}, grain)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(orleans_requests_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",grain=\"${grain}\"}, method)"
    }
   },
   {
    "name": "category",
    "label": "request's category",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=\"$grain\"}, category)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "grain rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grain) (rate(orleans_requests_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\"}[$__rate_interval])) ",
     "legendFormat": "{{grain}}"
    }
   ]
  },
  {
   "title": "grain rps on \"${grain}\" for method ${method}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(orleans_requests_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",grain=\"${grain}\",method=~\"${method}\"}[$__rate_interval])) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Heatmap of ${grain}:${method}",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(orleans_requests_duration_bucket{instance=~\"${instance}\",grain=\"${grain}\",method=~\"${method}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "average request duration of \"${grain}\" for methods \"${method}\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (method) (rate (orleans_requests_duration_sum{workspace=\"${workspace}\",instance=~\"${instance}\",grain=\"${grain}\",method=~\"${method}\"}[$__rate_interval]))) / (sum by (method) (rate (orleans_requests_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",grain=\"${grain}\",method=~\"${method}\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "flying requests by grains",
   "type": "timeseries",
   "description": "The request is \"in-flight\" if it is being processed by the grain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (grain) (orleans_requests_flying{instance=~\"${instance}\"})",
     "legendFormat": "{{grain}}"
    }
   ]
  },
  {
   "title": "flying request for $grain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (method) (orleans_requests_flying{instance=~\"${instance}\",grain=~\"${grain}\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "average request duration made by \"${grain}\" with \"${method}\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (category,name) (rate (nq_request_duration_sum{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=\"${grain}\",currentMethod=~\"$method\",category=~\"$category\"}[$__rate_interval]))) / (sum by (category,name) (rate (nq_request_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",currentGrain=\"${grain}\",currentMethod=~\"$method\",category=~\"$category\"}[$__rate_interval])))",
     "legendFormat": "{{category}} {{name}}"
    }
   ]
  },
  {
   "title": "Scrap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exception",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(orleans_exception_counter{workspace=\"${workspace}\",application_role=~\"${application_role}\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by (name) (orleans_metrics{workspace=\"${workspace}\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Request duration (controller-handled requests only)",
     "type": "heatmap",
     "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds_bucket{instance=~\"${instance}\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      { "expr": "orleans" }
     ]
    }
   ]
  }
 ]
}