{
 "title": "Requests v2",
 "tags": [
  "orleans",
  "dev"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(nq_request_duration_count, workspace)"
    }
   },
   {
    "name": "application_role",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\"}, application_role)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"${application_role}\"}, instance)"
    }
   },
   {
    "name": "grain",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",application_role=~\"$application_role\"}, currentGrain)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(orleans_requests_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",grain=~\"^${grain}$\"}, method)"
    }
   },
   {
    "name": "category",
    "query": {
     "query": "label_values(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"$grain\"}, category)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stuff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "grain rps for grains \"$grain\" and methods \"$method\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (currentGrain,category) (rate(nq_request_duration_count{workspace=\"${workspace}\",instance=~\"${instance}\",application_role=~\"$application_role\", category=~\"$category\", currentGrain=~\"${grain}\",currentMethod=~\"${method}\"}[$__rate_interval]))",
     "legendFormat": "{{currentGrain}} {{category}}"
    }
   ]
  },
  {
   "title": "flying requests by grains for grains \"$grain\" and methods \"$method\"",
   "type": "timeseries",
   "description": "The request is \"in-flight\" if it is being processed by the grain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (currentGrain,category) (max_over_time(nq_request_flying{instance=~\"${instance}\",application_role=~\"$application_role\", category=~\"$category\", currentGrain=~\"${grain}\",currentMethod=~\"${method}\"}[$__rate_interval]))",
     "legendFormat": "{{currentGrain}} {{category}}"
    }
   ]
  },
  { "title": "$category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "category" },
  {
   "title": "grain rps on \"${grain}\" \"$category\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (category,name) (rate(nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"^$grain$\",currentMethod=~\"^$method$\",category=~\"$category\"}[$__rate_interval])) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "average request duration on \"${grain}\" $category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (name) (rate (nq_request_duration_sum{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\"}[$__rate_interval]))) / (sum by (name) (rate (nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\"}[$__rate_interval])))",
     "legendFormat": "{{category}} {{name}}"
    }
   ]
  },
  {
   "title": "Heatmap of ${grain} $category",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(nq_request_duration_bucket{application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"^${grain}$\",currentMethod=~\"^$method$\",category=\"$category\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "flying request for $grain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by (category,name) (max_over_time(nq_request_flying{application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\"}[$__interval]))",
     "legendFormat": "{{category}} {{name}}"
    }
   ]
  },
  {
   "title": "success rate on \"${grain}\" $category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (name) (rate (nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\",success=\"True\"}[$__rate_interval]))) / (sum by (name) (rate (nq_request_duration_count{workspace=\"${workspace}\",application_role=~\"$application_role\",instance=~\"${instance}\",currentGrain=~\"${grain}\",currentMethod=~\"^$method$\",category=\"$category\"}[$__rate_interval])))",
     "legendFormat": "{{category}} {{name}}"
    }
   ]
  }
 ]
}